### ISSUE TITLE
Feature request - Separate the version deletion from account and files deletion.

### ISSUE THREAD

**Issue by gammexane** [FilenCloudDienste/filen-drive#106]
Maybe a stupid request but can we move the delete account option and delete all files to "another" section? 
I delete the versioned files very often and well, delete versioned and delete all are 10 pixels away.. 

![Screenshot from 2023-08-15 19-07-00](https://github.com/FilenCloudDienste/filen-drive/assets/509348/86b8bf04-b096-4013-ae3d-4fe5e644fdcc)

Thanks

**Comment by Dwynr** [comment]
It does not delete your account immediately. You have to confirm an email before aswell as a third confirmation on a separate linked page.
