### ISSUE TITLE
[FR] Add right-click menu entries related to Filen Desktop

### ISSUE THREAD

**Issue by DodoLeDev** [FilenCloudDienste/filen-drive#114]
Hi!
Directly related to [this issue](https://github.com/FilenCloudDienste/filen-desktop/issues/232), it could be interesting to allow the Filen Web Drive to interact with the client app thanks to a custom protocol.

Some options that could be integrated:
- Create new Sync Locations:
![image](https://github.com/FilenCloudDienste/filen-drive/assets/59477313/0c0e3430-9f6c-4bdb-8caf-5afa958b8eba)

- Open files with system programs:
![image](https://github.com/FilenCloudDienste/filen-drive/assets/59477313/2c3ec17d-ed62-4039-b7fb-9d2a22ebb5dd)

- Open local synced folder from the Filen Web Drive interface

To avoid potential data leaks due to link trackers or similar, the link argument will be encrypted using the account master key. This ensures that the app associated with the custom protocol can decrypt the data only if it has access to the same account master key.

**Comment by Dwynr** [comment]
Already answered in the relating issue. Closing for now!
