### ISSUE TITLE
Shared file name and size display truncated on small devices

### ISSUE THREAD

**Issue by auditum-mpa** [FilenCloudDienste/filen-drive#132]
When a public link is opened in the browser from a small device, like a smartphone, if the file does not allow any preview (for instance a doc file), then the file name and file size are truncated to 1 character.

**Comment by Dwynr** [comment]
Fixed, thanks for reporting!

**Comment by auditum-mpa** [comment]
Thanks.
Just note that if the links is invalid, the error message is still truncated.

**Comment by auditum-mpa** [comment]
> Fixed, thanks for reporting!

Thanks.
Just note that if the links is invalid, the error message is still truncated.
And if only the key part of the link is invalid, it is just printed "NaN undefined"...
