### ISSUE TITLE
Idea: Thumbnail creation during upload

### ISSUE THREAD

**Issue by xthrk** [FilenCloudDienste/filen-drive#14]
Referring to https://cdn.filen.io/whitepaper.pdf

3.2 Thumbnail generation
The client creates image thumbnails by downloading the encrypted data, decrypting it, resizing the resulting image, compressing it and then storing it in the client’s local storage, where it can be re-used. Video previews are created almost the same way, except for not downloading the whole video but just the first few chunks to save bandwidth and local storage space.

What about the idea of creating thumbnails directly during upload and saving them as metadata? Thumbnails are much smaller, quickly downloaded and decrypted with the metadata and so the thumbnails can be displayed faster. If necessary, you could make this optional in the user settings, whether thumbnails should be created during upload and saved as metadata or not.

**Comment by Dwynr** [comment]
We're already doing that in the mobile app. Will also be implemented in the Web Drive.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-drive/commit/ffe04f19204bce15fe0faaaa934484a3c2e962a9
