### ISSUE TITLE
Request: Full french translation

### ISSUE THREAD

**Issue by lyonelf** [FilenCloudDienste/filen-drive#34]
Have you projected to translate filen.io in french language?

If yes, i can do it !

**Comment by DanielProg39** [comment]
Filen is available in French, if it's not fully translated, feel free to contribute 😉

**Comment by lyonelf** [comment]
I don't talk about drive ( that i translated 2 weeks ago) but the commercial website filen.io

**Comment by DanielProg39** [comment]
Yup, regarding this, I'd also like to translate Filen sites and wiki to russian and Ukrainian, so I join you in your suggestion

**Comment by Dwynr** [comment]
We will open a new repository for this as soon as we can! I can ping here when it's opened.
