### ISSUE TITLE
[Feature Request] Incorporating Material You / Rounded Design

### ISSUE THREAD

**Issue by SimplyAnotherAnon** [FilenCloudDienste/filen-drive#4]
I'd love if it the designing around the Filen Drive was more rounded and modern similar to the styling of Google's Material Design 3 (You). Some aspects that could be changed in this regard would be items such as the left-side vertical bar on the Drive (below).
![Filen Drive](https://user-images.githubusercontent.com/115472706/203275624-adb80f5e-5dec-45ec-ae96-66ac1fb6e470.png)
Changing it up to include Chips and Rounded corners, vertically stacked would look cleaner and more "aesthetic" as opposed to the current design which has remained virtually unchanged and while perfectly use-able, _feels_ outdated. 
![Material You SideBar Unexpanded](https://user-images.githubusercontent.com/115472706/203275890-885e9de2-1386-43c2-b40c-bff1bf7da3c1.png)
As for the drop-down menus when you click on folders, an expanded menu with rounded chips could be used as shown in the example below
![Material You SideBar Expanded](https://user-images.githubusercontent.com/115472706/203276053-b0911fcd-2f48-486d-9929-a75490615274.png)

 In addition, incorporating some other customization aspects like allowing the user to set a specific accent color theme across the website, especially as the white/grey theming across the Drive can get a bit stale, would be greatly appreciated.

**Comment by Dwynr** [comment]
The design is always evolving, we'll take your suggestions into consideration. Thanks
