### ISSUE TITLE
[Bug] File size is not encrypted

### ISSUE THREAD

**Issue by dragani** [FilenCloudDienste/filen-drive#45]
In the Security Whitepaper it says:

> Even folder names, file metadata (such as mime type, size etc.) are encrypted.

However, when you login to Filen web with Chrome, open the browser's developer tools (F12) and inspect the response data while you open a folder, you can see that the file size is received in clear text from the server. Is this intentional?

**Comment by Dwynr** [comment]
Yes, since we store the actual file, the size is always visible to us. Encryption only adds a very small overhead of a few bytes.

**Comment by dragani** [comment]
As you split the files into chunks of ~1MB, you are natively obscuring the original size of files above 1MB. So, I was just wondering if there is any reason you _need_ to store the actual file size,
