### ISSUE TITLE
[Bug] Avoid image over zooming

### ISSUE THREAD

**Issue by carlosdariodev** [FilenCloudDienste/filen-drive#48]
If you zoom-out a lot in an image, it inverts the image on the Y axis, and then starts zooming it. There should probably be a zoom-out limit, maximum 100% size of the image I would say.

Tested on Firefox 110.0 (64-bit).

**Comment by DanielProg39** [comment]
Yup, I saw that and it's kinda funny)

**Comment by carlosdariodev** [comment]
Also, I can click and move the image outside of the view. It should be fix centered horizontally when there is space of the sides, and fix centered vertically whenever there is space on the top and bottom.

**Comment by DanielProg39** [comment]
Agreed, it's a well-known problem
