### ISSUE TITLE
Feature request : share writable folders with other Filen users

### ISSUE THREAD

**Issue by DodoLeDev** [FilenCloudDienste/filen-drive#51]
Hi!
First of all, THANK YOU SO MUCH for this incredible encrypted cloud! ♥

I was just wondering if a feature allowing us to share folders with other users **in such a way they could edit its contents** is planned in a near future...

Currently we can only provide a **read-only access** to other users...

_Best regards!_

**Comment by auditum-mpa** [comment]
Thanks for this great cloud initiative!

I would also find this feature very useful! Looking forward to seeing it on a next release.

**Comment by Dwynr** [comment]
We are already working on this exact feature. Check out our blog to learn more about it.
