### ISSUE TITLE
very poor score at https://observatory.mozilla.org/ a set of tools to analyze website's https configuration

### ISSUE THREAD

**Issue by gpdevsoft** [FilenCloudDienste/filen-drive#6]
You are doing a great job with new web UI, so i tried to run Mozilla HTTP Observatory service test (a set of tools to analyze a website and inform if you are utilizing the best available methods to secure it) I noticed that the score obtained is quite low, F in a scale from A to F, when you have time and if you think it useful you can also improve this aspect of safety.

Thanks and good job.

here you can find results for the login page https://observatory.mozilla.org/analyze/drive.filen.io

**Comment by gpdevsoft** [comment]
Is it possible that no one is interested in this topic? a secure cloud that adopts a very insecure configuration for connecting to its servers doesn't seem like a negligible detail to me, however don't lose hope perhaps by the end of the year you will find the time to read this post

**Comment by Dwynr** [comment]
Scores like this one don't really mean much to he fair. Just look at Googles Score for example: https://observatory.mozilla.org/analyze/google.com

Yet we improved it to a B. Will add further improvements in the future.
