### ISSUE TITLE
markdown get blank with "#"

### ISSUE THREAD

**Issue by alexxsam** [FilenCloudDienste/filen-drive#60]
Hi

Mardown files are readable and rendered,
but when I put a # at the beginning of a line, the webpage get full blank,
and when I remove a # there is often a popup saying "Delete, Are you sure you want to delete 1 items?"

reproduce : 
- on drive.filen.io, create text file
- name it test.md
- put "#" alone

**Comment by Dwynr** [comment]
Thanks for letting us know, will be fixed asap.
