### ISSUE TITLE
Release as a desktop app

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-drive#78]
Filen Desktop is useful for file syncing. This is good for browsing the files in the cloud and uploading/downloading files, and renaming and deleting files.

Using the web client on the websites is less secure than using a desktop app.

Please release this as a desktop app. Therefore no need to have to use the web client.

**Comment by DanielProg39** [comment]
As for me, it's better to implement virtual drive mounting, which is already on the roadmap

**Comment by trymeouteh** [comment]
> As for me, it's better to implement virtual drive mounting, which is already on the roadmap

How do you upload files to a virtual mounted drive in the file explorer. Plus there are so many different files explorers out especially on Linux.

**Comment by DanielProg39** [comment]
It's pretty easy: you simply move or copy your file to remote location, just like it's a hard drive in your computer. Pretty much every file explorer supports this, so there's no problem.

**Comment by trymeouteh** [comment]
Not against there being virtual drive mounting. However a FIlen Drive client would be more secure since your cloud storage is no mounted in your file system. And no need to support every single file manager out there. On linux there are several file managers out there, which is quite a bit of file managers to support. Filen Drive will be one codebase that supports Windows, macOS and all Linux distros if the linux app is released as an AppImage or Flatpak.

**Comment by DanielProg39** [comment]
You got it wrong. There's no need to create a program for each file manager to support the Filen Drive. Every file manager already has different ways to access remote storage: FTP, NFS, Samba, SSH, WebDAV... These are standards that are supported everywhere, so if you tell the system to connect to certain WebDAV instance, or mount any cloud storage using Rclone, any file manager will automatically recognize and show it.

**Comment by trymeouteh** [comment]
But Filen is E2EE, wouldnt these protocols not work since they are not designed for E2EE?

**Comment by DanielProg39** [comment]
Well, that's true, but if it's on their roadmap, it might be possible. I'm not sure how they'd do it with WebDAV, but with Rclone it's basically possible, and Mega is a good example. I agree about the security concerns. And the idea of a desktop client is not bad. It would be great to build it on top of the existing Filen desktop application, as you can already see your cloud file system when you select a folder to sync or enable selective sync, and it would be a great replacement for the "open website" button.

**Comment by Dwynr** [comment]
We are looking to combine the web drive and desktop interfaces in the future. Drive mounting is also still on the roadmap (1st priority).
