### ISSUE TITLE
Web Login screen: "Error: Please enter your two factor authentication code"

### ISSUE THREAD

**Issue by gammexane** [FilenCloudDienste/filen-drive#87]
Hello, this is not a critical bug, it is just annoying.
I have activated 2FA since day one and I have this "error" since then, first I thought it was due to Bitwarden, but no, it happens in every login.

1) I enter in drive.filen.io
2) I enter my user and pass, I press enter and I get the error i mentioned in the subject. "Error: Please enter your 2 Factor auth. core".
3) Only after this error, I get the 2FA input field in which I enter my code and I can access Filen. 

In the EVENT section I always get a login error also because of this:
![Screenshot from 2023-05-15 17-18-03](https://github.com/FilenCloudDienste/filen-drive/assets/509348/cff307b5-5027-4451-b0d1-f5ee207a1744)

**Comment by Dwynr** [comment]
Thanks for reporting. Will be fixed asap.
