### ISSUE TITLE
[Feature Wunsch] Webdav Zugang

### ISSUE THREAD

**Issue by morpheasgr** [FilenCloudDienste/filen-drive#89]
Hallo allerseits,

finds echt cool dass der Dienst, den ich gestern Abend beim Stöbern entdeckt habe zufälligerweise aus Deutschland ist.

Der Feature-Wunsch den ich aüßere wurde in anderen Formen schonmals angesprochen zB auf Reddit, es handelt sich um Filesystem Integration bzw dass man den Dienst als Netzwerkspeicher oder per Dateimanager 'mount'en kann.

Webdav wäre da eine der klügsten Entscheidungen.

Hier nochmal wie ein anderer Nutzer vorgeschlagej hat, Rclone auf Desktop (https://github.com/rclone/rclone) oder rclone Android (https://github.com/newhinton/extRact - aktive 'Fork' von RCX)

jedoch wäre eine Standard Webdav Integration sinnvoll, denn dann kann man den dienst bei Zich Dateimanagern anbinden (bei Android zum beispiel über MiXplorer - freeware bei XDA Developers) bzw unterstützt Rclone auf allen Desktop-Betriebsystemen Webdav vom Hause aus.

Also schlage ich eine Webdav Integration als major Feature vor.

Habe mir heute den 100GB lifetime Pass geholt und plane definitiv auf 2TB umzusteigen wenn allew jut läuft. liebe Grüße,

A.

**Comment by DanielProg39** [comment]
Ja, diese Funktion ist geplant, aber da Filen E2EE ist, ist es ziemlich schwierig zu implementieren, so dass Sie Ihren eigenen lokalen WebDAV-Server einrichten müssen, und diese Funktion soll vorerst nur ein Befehlszeilen-Client sein. Bleiben Sie also dran.

**Comment by morpheasgr** [comment]
yo, alles verständlich. Durchaus kein Thema. :) Man kann ja syncen. Hoffe dass die Dateiencjedoch exht Safe sind, da ich es planne Musikproduktions-Projektdateien darüber syncen zu lassen, von Studio A zu Studio B und gegebenfalls ne MP3 oder WAV von Handys abzuspielen. Datenverlust wäre ein Drama, obwohl es sich um Backup Kopien handeln wird.

Liebe Grüße nochmals,

Angelo

**Comment by Dwynr** [comment]
Funktion ist geplant, wird auch kommen. Dauert nur ein wenig länger, da wir alles selber schreiben müssen wegen unserer Ende zu Ende Verschlüsselung. Ist nebenbei auch die falsche Repository (desktop Repo passt eher). WebDAV, wie auch FTP oder SMB müsste selber gehostet werden um die Verschlüsselung nicht zu brechen.

**Comment by Dwynr** [comment]
Schließe den Issue vorerst, Progress wird in einer eigenen Repo oder unserer Desktop Client Repo kommen.
